version: "3.8"

services:
  app:
    build: .
    command: bash start.sh
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./config.py:/usr/src/app/config.py:ro
      - ./accounts:/usr/src/app/accounts
      - ./downloads:/usr/src/app/downloads
