services:
  app:
    build: .
    command: bash start.sh
    restart: unless-stopped
    dns:
      - 8.8.8.8
      - 8.8.4.4
    ports:
      - "8080:8080"
    volumes:
      - ./config.py:/usr/src/app/config.py:ro
      - ./accounts:/usr/src/app/accounts
      - ./downloads:/usr/src/app/downloads
